import type { Sector, Theme } from "./types";

const freezeTheme = (theme: Theme): Readonly<Theme> => Object.freeze(theme);

const freezeSector = (sector: Sector): Readonly<Sector> =>
  Object.freeze({
    ...sector,
    relatedThemeIds: Object.freeze([...sector.relatedThemeIds]),
    aliases: Object.freeze([...sector.aliases])
  });

const themeConfig = [
  { id: "ai-computing", name: "AI算力", shortName: "AI算力", color: "#c45baa" },
  { id: "robotics-physical-ai", name: "机器人（物理AI）", shortName: "机器人", color: "#d89a38" },
  { id: "low-altitude-economy", name: "低空经济", shortName: "低空经济", color: "#3b82c4" },
  { id: "semiconductors", name: "半导体", shortName: "半导体", color: "#b86adf" },
  { id: "new-energy", name: "新能源", shortName: "新能源", color: "#4a9fd4" },
  { id: "defense-aerospace", name: "军工/商业航天", shortName: "军工航天", color: "#7f91a6" },
  { id: "innovative-medicine", name: "创新药/医药", shortName: "创新药", color: "#9b6ad8" },
  { id: "new-energy-vehicles", name: "新能源汽车/智能驾驶", shortName: "新能源车", color: "#5b8cc4" },
  { id: "consumer-electronics", name: "消费电子/VR", shortName: "消费电子", color: "#ff8c42" },
  { id: "digital-economy", name: "数字经济/数据要素", shortName: "数字经济", color: "#6c5ce7" },
  { id: "fintech", name: "金融科技", shortName: "金融科技", color: "#7c6bc4" }
] satisfies readonly Theme[];

export const themes: readonly Readonly<Theme>[] = Object.freeze(themeConfig.map(freezeTheme));

const sectorConfig = [
  // ─── AI算力 (9 sectors) ───
  {
    id: "ai-computing",
    name: "AI算力",
    shortName: "AI算力",
    primaryThemeId: "ai-computing",
    subThemeId: "ai-computing-infra",
    relatedThemeIds: ["ai-computing"],
    aliases: ["人工智能算力", "算力主线"],
    industrialChainRole: "主线中心",
    isThemeCenter: true,
    relationshipNote: "AI主线核心，承接大模型训练和推理需求。"
  },
  {
    id: "optical-modules",
    name: "光模块",
    shortName: "光模块",
    primaryThemeId: "ai-computing",
    subThemeId: "optical-interconnect",
    relatedThemeIds: ["ai-computing"],
    aliases: ["高速光模块"],
    industrialChainRole: "算力互联",
    isThemeCenter: false,
    relationshipNote: "AI数据中心高速互联的核心环节，常与算力主线共振。"
  },
  {
    id: "cpo",
    name: "CPO",
    shortName: "CPO",
    primaryThemeId: "ai-computing",
    subThemeId: "optical-interconnect",
    relatedThemeIds: ["ai-computing"],
    aliases: ["共封装光学"],
    industrialChainRole: "光互联技术",
    isThemeCenter: false,
    relationshipNote: "光互联技术分支，靠近光模块和AI算力。"
  },
  {
    id: "liquid-cooled-servers",
    name: "液冷服务器",
    shortName: "液冷",
    primaryThemeId: "ai-computing",
    subThemeId: "liquid-cooling-infra",
    relatedThemeIds: ["ai-computing"],
    aliases: ["服务器液冷"],
    industrialChainRole: "算力基础设施",
    isThemeCenter: false,
    relationshipNote: "高功耗算力基础设施的散热分支。"
  },
  {
    id: "domestic-computing",
    name: "国产算力",
    shortName: "国产算力",
    primaryThemeId: "ai-computing",
    subThemeId: "domestic-substitution",
    relatedThemeIds: ["ai-computing"],
    aliases: ["国产AI芯片", "信创算力"],
    industrialChainRole: "国产替代",
    isThemeCenter: false,
    relationshipNote: "国产替代与AI算力需求叠加。"
  },
  {
    id: "data-centers",
    name: "数据中心",
    shortName: "数据中心",
    primaryThemeId: "ai-computing",
    subThemeId: "liquid-cooling-infra",
    relatedThemeIds: ["ai-computing"],
    aliases: ["IDC"],
    industrialChainRole: "算力载体",
    isThemeCenter: false,
    relationshipNote: "AI算力落地的基础设施载体。"
  },
  {
    id: "ai-chip-design",
    name: "AI芯片设计",
    shortName: "AI芯片设计",
    primaryThemeId: "ai-computing",
    subThemeId: "domestic-substitution",
    relatedThemeIds: ["ai-computing", "semiconductors"],
    aliases: ["AI芯片", "国产AI芯片设计"],
    industrialChainRole: "国产替代",
    isThemeCenter: false,
    relationshipNote: "国产AI芯片设计分支，与半导体芯片设计高度交叉。"
  },
  {
    id: "aigc",
    name: "AIGC",
    shortName: "AIGC",
    primaryThemeId: "ai-computing",
    subThemeId: "ai-applications",
    relatedThemeIds: ["ai-computing", "digital-economy"],
    aliases: ["生成式AI", "大模型应用"],
    industrialChainRole: "AI应用",
    isThemeCenter: false,
    relationshipNote: "生成式AI应用层，连接算力需求与数字经济场景。"
  },
  {
    id: "ai-agent",
    name: "AI Agent",
    shortName: "AI Agent",
    primaryThemeId: "ai-computing",
    subThemeId: "ai-applications",
    relatedThemeIds: ["ai-computing", "digital-economy", "robotics-physical-ai"],
    aliases: ["智能体", "AI智能体"],
    industrialChainRole: "AI应用",
    isThemeCenter: false,
    relationshipNote: "AI智能体应用层，连接算力、软件和机器人执行能力。"
  },

  // ─── 机器人（物理AI） (8 sectors) ───
  {
    id: "robotics-physical-ai",
    name: "机器人（物理AI）",
    shortName: "机器人",
    primaryThemeId: "robotics-physical-ai",
    subThemeId: "core-components",
    relatedThemeIds: ["robotics-physical-ai", "ai-computing"],
    aliases: ["物理AI", "人形机器人"],
    industrialChainRole: "主线中心",
    isThemeCenter: true,
    relationshipNote: "AI能力向物理世界延伸的核心主线。"
  },
  {
    id: "reducers",
    name: "减速器",
    shortName: "减速器",
    primaryThemeId: "robotics-physical-ai",
    subThemeId: "core-components",
    relatedThemeIds: ["robotics-physical-ai"],
    aliases: ["谐波减速器"],
    industrialChainRole: "运动控制",
    isThemeCenter: false,
    relationshipNote: "机器人运动控制核心零部件。"
  },
  {
    id: "servo-systems",
    name: "伺服系统",
    shortName: "伺服",
    primaryThemeId: "robotics-physical-ai",
    subThemeId: "motion-control",
    relatedThemeIds: ["robotics-physical-ai"],
    aliases: ["伺服电机"],
    industrialChainRole: "运动控制",
    isThemeCenter: false,
    relationshipNote: "机器人执行控制的重要分支。"
  },
  {
    id: "sensors",
    name: "传感器",
    shortName: "传感器",
    primaryThemeId: "robotics-physical-ai",
    subThemeId: "perception-layer",
    relatedThemeIds: ["robotics-physical-ai", "low-altitude-economy"],
    aliases: ["感知硬件"],
    industrialChainRole: "感知层",
    isThemeCenter: false,
    relationshipNote: "机器人和低空设备感知层的共用环节。"
  },
  {
    id: "machine-vision",
    name: "机器视觉",
    shortName: "机器视觉",
    primaryThemeId: "robotics-physical-ai",
    subThemeId: "perception-layer",
    relatedThemeIds: ["robotics-physical-ai", "ai-computing"],
    aliases: ["工业视觉"],
    industrialChainRole: "感知算法",
    isThemeCenter: false,
    relationshipNote: "AI识别能力和机器人感知能力的交叉分支。"
  },
  {
    id: "actuators",
    name: "执行器",
    shortName: "执行器",
    primaryThemeId: "robotics-physical-ai",
    subThemeId: "motion-control",
    relatedThemeIds: ["robotics-physical-ai"],
    aliases: ["线性执行器"],
    industrialChainRole: "执行层",
    isThemeCenter: false,
    relationshipNote: "机器人末端动作和关节控制的关键部件。"
  },
  {
    id: "industrial-robotics",
    name: "工业机器人",
    shortName: "工业机器人",
    primaryThemeId: "robotics-physical-ai",
    subThemeId: "application-scenarios",
    relatedThemeIds: ["robotics-physical-ai"],
    aliases: ["工业自动化机器人", "产线机器人"],
    industrialChainRole: "应用场景",
    isThemeCenter: false,
    relationshipNote: "机器人在工业制造场景的落地应用分支。"
  },
  {
    id: "humanoid-robot",
    name: "人形机器人",
    shortName: "人形机器人",
    primaryThemeId: "robotics-physical-ai",
    subThemeId: "application-scenarios",
    relatedThemeIds: ["robotics-physical-ai", "ai-computing"],
    aliases: ["仿人机器人"],
    industrialChainRole: "应用场景",
    isThemeCenter: false,
    relationshipNote: "人形机器人整机制造分支，集成为多学科技术载体。"
  },

  // ─── 低空经济 (7 sectors) ───
  {
    id: "low-altitude-economy",
    name: "低空经济",
    shortName: "低空经济",
    primaryThemeId: "low-altitude-economy",
    subThemeId: "aircraft-control",
    relatedThemeIds: ["low-altitude-economy"],
    aliases: ["低空主线"],
    industrialChainRole: "主线中心",
    isThemeCenter: true,
    relationshipNote: "政策、航空器、运营和空域基础设施共同构成的主题中心。"
  },
  {
    id: "evtol",
    name: "eVTOL",
    shortName: "eVTOL",
    primaryThemeId: "low-altitude-economy",
    subThemeId: "aircraft-control",
    relatedThemeIds: ["low-altitude-economy"],
    aliases: ["电动垂直起降"],
    industrialChainRole: "航空器",
    isThemeCenter: false,
    relationshipNote: "低空经济最具辨识度的航空器分支。"
  },
  {
    id: "flight-control-systems",
    name: "飞控系统",
    shortName: "飞控",
    primaryThemeId: "low-altitude-economy",
    subThemeId: "drone-systems",
    relatedThemeIds: ["low-altitude-economy", "robotics-physical-ai"],
    aliases: ["飞行控制"],
    industrialChainRole: "控制系统",
    isThemeCenter: false,
    relationshipNote: "低空航空器控制核心，也与机器人控制逻辑相近。"
  },
  {
    id: "drones",
    name: "无人机",
    shortName: "无人机",
    primaryThemeId: "low-altitude-economy",
    subThemeId: "drone-systems",
    relatedThemeIds: ["low-altitude-economy"],
    aliases: ["工业无人机"],
    industrialChainRole: "应用载体",
    isThemeCenter: false,
    relationshipNote: "低空应用落地最成熟的载体。"
  },
  {
    id: "general-aviation-operations",
    name: "通航运营",
    shortName: "通航",
    primaryThemeId: "low-altitude-economy",
    subThemeId: "operations-infra",
    relatedThemeIds: ["low-altitude-economy"],
    aliases: ["低空运营"],
    industrialChainRole: "运营场景",
    isThemeCenter: false,
    relationshipNote: "低空商业化场景和运营网络。"
  },
  {
    id: "air-traffic-systems",
    name: "空管系统",
    shortName: "空管",
    primaryThemeId: "low-altitude-economy",
    subThemeId: "low-alt-comm",
    relatedThemeIds: ["low-altitude-economy"],
    aliases: ["低空空管"],
    industrialChainRole: "基础设施",
    isThemeCenter: false,
    relationshipNote: "低空飞行秩序和基础设施分支。"
  },
  {
    id: "low-altitude-communication",
    name: "低空通信",
    shortName: "低空通信",
    primaryThemeId: "low-altitude-economy",
    subThemeId: "low-alt-comm",
    relatedThemeIds: ["low-altitude-economy", "semiconductors"],
    aliases: ["低空通导监", "低空网络"],
    industrialChainRole: "运营基建",
    isThemeCenter: false,
    relationshipNote: "低空飞行通信导航监视网络基础设施，与半导体射频器件交叉。"
  },

  // ─── 半导体 (8 sectors) ───
  {
    id: "semiconductors",
    name: "半导体",
    shortName: "半导体",
    primaryThemeId: "semiconductors",
    subThemeId: "design-manufacturing",
    relatedThemeIds: ["semiconductors"],
    aliases: ["芯片产业", "集成电路"],
    industrialChainRole: "主线中心",
    isThemeCenter: true,
    relationshipNote: "半导体主线中心，连接芯片设计、制造、材料设备和封装环节。"
  },
  {
    id: "chip-design",
    name: "芯片设计",
    shortName: "芯片设计",
    primaryThemeId: "semiconductors",
    subThemeId: "design-manufacturing",
    relatedThemeIds: ["semiconductors", "ai-computing"],
    aliases: ["IC设计", "Fabless"],
    industrialChainRole: "上游设计",
    isThemeCenter: false,
    relationshipNote: "半导体产业链上游设计环节，也承接AI算力芯片需求。"
  },
  {
    id: "wafer-fabrication",
    name: "晶圆制造",
    shortName: "晶圆制造",
    primaryThemeId: "semiconductors",
    subThemeId: "design-manufacturing",
    relatedThemeIds: ["semiconductors"],
    aliases: ["晶圆代工", "Foundry"],
    industrialChainRole: "制造环节",
    isThemeCenter: false,
    relationshipNote: "将芯片设计转化为晶圆产品的核心制造环节。"
  },
  {
    id: "semiconductor-equipment",
    name: "半导体设备",
    shortName: "半导体设备",
    primaryThemeId: "semiconductors",
    subThemeId: "equipment-materials",
    relatedThemeIds: ["semiconductors"],
    aliases: ["芯片设备", "制造设备"],
    industrialChainRole: "制造装备",
    isThemeCenter: false,
    relationshipNote: "支撑晶圆制造和先进制程扩产的关键装备分支。"
  },
  {
    id: "photoresist",
    name: "光刻胶",
    shortName: "光刻胶",
    primaryThemeId: "semiconductors",
    subThemeId: "materials-process",
    relatedThemeIds: ["semiconductors"],
    aliases: ["半导体材料", "光刻材料"],
    industrialChainRole: "材料",
    isThemeCenter: false,
    relationshipNote: "半导体制造中的关键材料，直接关联光刻工艺国产化。"
  },
  {
    id: "advanced-packaging",
    name: "先进封装",
    shortName: "先进封装",
    primaryThemeId: "semiconductors",
    subThemeId: "advanced-packaging-st",
    relatedThemeIds: ["semiconductors", "ai-computing"],
    aliases: ["Chiplet封装", "高端封装"],
    industrialChainRole: "后道封装",
    isThemeCenter: false,
    relationshipNote: "半导体后道能力升级分支，也服务AI芯片算力密度提升。"
  },
  {
    id: "chiplet",
    name: "Chiplet",
    shortName: "Chiplet",
    primaryThemeId: "semiconductors",
    subThemeId: "chip-arch",
    relatedThemeIds: ["semiconductors", "ai-computing"],
    aliases: ["小芯片", "芯粒"],
    industrialChainRole: "先进封装",
    isThemeCenter: false,
    relationshipNote: "Chiplet异构集成分支，是先进封装的核心技术方向。"
  },
  {
    id: "hbm",
    name: "HBM",
    shortName: "HBM",
    primaryThemeId: "semiconductors",
    subThemeId: "chip-arch",
    relatedThemeIds: ["semiconductors", "ai-computing"],
    aliases: ["高带宽内存", "HBM内存"],
    industrialChainRole: "先进封装",
    isThemeCenter: false,
    relationshipNote: "AI算力核心存储器分支，与先进封装高度耦合。"
  },

  // ─── 新能源 (7 sectors) ───
  {
    id: "new-energy",
    name: "新能源",
    shortName: "新能源",
    primaryThemeId: "new-energy",
    subThemeId: "power-generation",
    relatedThemeIds: ["new-energy"],
    aliases: ["能源转型", "绿色能源"],
    industrialChainRole: "主线中心",
    isThemeCenter: true,
    relationshipNote: "新能源主线中心，覆盖发电、储能、动力电池和终端补能设施。"
  },
  {
    id: "photovoltaics",
    name: "光伏",
    shortName: "光伏",
    primaryThemeId: "new-energy",
    subThemeId: "power-generation",
    relatedThemeIds: ["new-energy", "semiconductors"],
    aliases: ["太阳能", "光伏组件"],
    industrialChainRole: "发电设备",
    isThemeCenter: false,
    relationshipNote: "新能源发电设备分支，部分材料和制造工艺与半导体相关。"
  },
  {
    id: "wind-power",
    name: "风电",
    shortName: "风电",
    primaryThemeId: "new-energy",
    subThemeId: "power-generation",
    relatedThemeIds: ["new-energy"],
    aliases: ["风力发电", "海上风电"],
    industrialChainRole: "发电设备",
    isThemeCenter: false,
    relationshipNote: "新能源发电设备分支，提供集中式和海上清洁电力供给。"
  },
  {
    id: "power-batteries",
    name: "动力电池",
    shortName: "动力电池",
    primaryThemeId: "new-energy",
    subThemeId: "battery-tech",
    relatedThemeIds: ["new-energy"],
    aliases: ["锂电池", "电池产业链"],
    industrialChainRole: "储能部件",
    isThemeCenter: false,
    relationshipNote: "新能源车和储能系统的核心部件，连接电化学储能需求。"
  },
  {
    id: "energy-storage",
    name: "储能",
    shortName: "储能",
    primaryThemeId: "new-energy",
    subThemeId: "storage-battery",
    relatedThemeIds: ["new-energy"],
    aliases: ["新型储能", "储能系统"],
    industrialChainRole: "储能系统",
    isThemeCenter: false,
    relationshipNote: "承接新能源发电波动性的系统环节，是电网消纳的重要支撑。"
  },
  {
    id: "charging-infrastructure",
    name: "充电基础设施",
    shortName: "充电桩",
    primaryThemeId: "new-energy",
    subThemeId: "charging-infra",
    relatedThemeIds: ["new-energy"],
    aliases: ["充电桩", "补能设施"],
    industrialChainRole: "终端设施",
    isThemeCenter: false,
    relationshipNote: "新能源车终端补能设施，连接电网、储能和车端应用。"
  },
  {
    id: "solid-state-batteries",
    name: "固态电池",
    shortName: "固态电池",
    primaryThemeId: "new-energy",
    subThemeId: "battery-tech",
    relatedThemeIds: ["new-energy", "semiconductors"],
    aliases: ["全固态电池", "固态锂电池"],
    industrialChainRole: "储能电池",
    isThemeCenter: false,
    relationshipNote: "下一代储能电池技术分支，材料体系与半导体有交叉。"
  },

  // ─── 军工/商业航天 (7 sectors) ───
  {
    id: "defense-aerospace",
    name: "军工/商业航天",
    shortName: "军工航天",
    primaryThemeId: "defense-aerospace",
    subThemeId: "launch-communication",
    relatedThemeIds: ["defense-aerospace"],
    aliases: ["军工航天", "国防航天"],
    industrialChainRole: "主线中心",
    isThemeCenter: true,
    relationshipNote: "军工和商业航天主线中心，统合发射、卫星、导航、材料和电子分支。"
  },
  {
    id: "commercial-aerospace",
    name: "商业航天",
    shortName: "商业航天",
    primaryThemeId: "defense-aerospace",
    subThemeId: "launch-communication",
    relatedThemeIds: ["defense-aerospace", "low-altitude-economy"],
    aliases: ["商业火箭", "民营航天"],
    industrialChainRole: "航天发射",
    isThemeCenter: false,
    relationshipNote: "航天发射和运载能力分支，与低空经济共同体现空天产业扩容。"
  },
  {
    id: "satellite-internet",
    name: "卫星互联网",
    shortName: "卫星互联网",
    primaryThemeId: "defense-aerospace",
    subThemeId: "launch-communication",
    relatedThemeIds: ["defense-aerospace", "semiconductors"],
    aliases: ["低轨卫星", "星联网"],
    industrialChainRole: "通信网络",
    isThemeCenter: false,
    relationshipNote: "商业航天通信网络分支，对卫星制造和高可靠芯片有联动需求。"
  },
  {
    id: "navigation-systems",
    name: "导航系统",
    shortName: "导航",
    primaryThemeId: "defense-aerospace",
    subThemeId: "navigation-electronics",
    relatedThemeIds: ["defense-aerospace", "low-altitude-economy"],
    aliases: ["北斗导航", "卫星导航"],
    industrialChainRole: "导航定位",
    isThemeCenter: false,
    relationshipNote: "空天导航定位分支，也支撑低空飞行器监管和路径规划。"
  },
  {
    id: "defense-electronics",
    name: "军工电子",
    shortName: "军工电子",
    primaryThemeId: "defense-aerospace",
    subThemeId: "navigation-electronics",
    relatedThemeIds: ["defense-aerospace", "semiconductors"],
    aliases: ["国防电子", "军用电子"],
    industrialChainRole: "军工电子",
    isThemeCenter: false,
    relationshipNote: "国防信息化和航天装备电子化分支，与半导体国产化高度相关。"
  },
  {
    id: "aerospace-materials",
    name: "航天材料",
    shortName: "航天材料",
    primaryThemeId: "defense-aerospace",
    subThemeId: "materials-equipment",
    relatedThemeIds: ["defense-aerospace"],
    aliases: ["高温合金", "复合材料"],
    industrialChainRole: "高端材料",
    isThemeCenter: false,
    relationshipNote: "军工航天装备的高端材料分支，支撑轻量化和极端环境可靠性。"
  },
  {
    id: "defense-informatics",
    name: "军工信息化",
    shortName: "军工信息化",
    primaryThemeId: "defense-aerospace",
    subThemeId: "defense-informatics-st",
    relatedThemeIds: ["defense-aerospace", "ai-computing", "digital-economy"],
    aliases: ["国防信息化", "军事信息化"],
    industrialChainRole: "导航电子",
    isThemeCenter: false,
    relationshipNote: "军工信息化指挥控制系统分支，与AI和数字经济技术交叉。"
  },

  // ─── 创新药/医药 (6 sectors) ───
  {
    id: "innovative-medicine",
    name: "创新药/医药",
    shortName: "医药主线",
    primaryThemeId: "innovative-medicine",
    subThemeId: "drug-rd",
    relatedThemeIds: ["innovative-medicine"],
    aliases: ["创新医药", "医药主线"],
    industrialChainRole: "主线中心",
    isThemeCenter: true,
    relationshipNote: "医药创新主线中心，连接药物研发、外包服务、器械和生物制造。"
  },
  {
    id: "innovative-drugs",
    name: "创新药",
    shortName: "创新药",
    primaryThemeId: "innovative-medicine",
    subThemeId: "drug-rd",
    relatedThemeIds: ["innovative-medicine"],
    aliases: ["新药研发", "Biotech"],
    industrialChainRole: "药物研发",
    isThemeCenter: false,
    relationshipNote: "医药主题的药物研发分支，聚焦新靶点、新机制和临床价值兑现。"
  },
  {
    id: "cro-cdmo",
    name: "CRO/CDMO",
    shortName: "CRO/CDMO",
    primaryThemeId: "innovative-medicine",
    subThemeId: "drug-rd",
    relatedThemeIds: ["innovative-medicine"],
    aliases: ["医药外包", "CXO"],
    industrialChainRole: "研发外包",
    isThemeCenter: false,
    relationshipNote: "创新药研发和生产外包分支，服务从临床前到商业化生产的效率提升。"
  },
  {
    id: "medical-devices",
    name: "医疗器械",
    shortName: "医疗器械",
    primaryThemeId: "innovative-medicine",
    subThemeId: "device-biology",
    relatedThemeIds: ["innovative-medicine", "semiconductors"],
    aliases: ["高端器械", "医疗设备"],
    industrialChainRole: "医疗器械",
    isThemeCenter: false,
    relationshipNote: "医药健康硬件分支，高端设备和检测仪器与芯片及传感技术存在交叉。"
  },
  {
    id: "synthetic-biology",
    name: "合成生物",
    shortName: "合成生物",
    primaryThemeId: "innovative-medicine",
    subThemeId: "device-biology",
    relatedThemeIds: ["innovative-medicine", "new-energy"],
    aliases: ["生物制造", "合成生物学"],
    industrialChainRole: "生物制造",
    isThemeCenter: false,
    relationshipNote: "医药与制造交叉分支，可用于药物、材料和绿色制造场景。"
  },
  {
    id: "traditional-chinese-medicine",
    name: "中药",
    shortName: "中药",
    primaryThemeId: "innovative-medicine",
    subThemeId: "traditional-medicine",
    relatedThemeIds: ["innovative-medicine"],
    aliases: ["中成药", "传统中药"],
    industrialChainRole: "防御医药",
    isThemeCenter: false,
    relationshipNote: "医药主题中的防御属性分支，体现品牌、渠道和稳健现金流特征。"
  },

  // ─── 新能源汽车/智能驾驶 (8 sectors) ───
  {
    id: "new-energy-vehicles",
    name: "新能源汽车/智能驾驶",
    shortName: "新能源车",
    primaryThemeId: "new-energy-vehicles",
    subThemeId: "vehicle-powertrain",
    relatedThemeIds: ["new-energy-vehicles"],
    aliases: ["新能源车主线"],
    industrialChainRole: "主线中心",
    isThemeCenter: true,
    relationshipNote: "新能源车与智能驾驶主题中心，覆盖整车制造、三电系统和智能驾驶技术。"
  },
  {
    id: "vehicle-manufacturing",
    name: "整车制造",
    shortName: "整车制造",
    primaryThemeId: "new-energy-vehicles",
    subThemeId: "vehicle-powertrain",
    relatedThemeIds: ["new-energy-vehicles"],
    aliases: ["新能源整车", "车企"],
    industrialChainRole: "整车制造",
    isThemeCenter: false,
    relationshipNote: "新能源汽车整车组装制造环节。"
  },
  {
    id: "electric-drive-systems",
    name: "电驱动系统",
    shortName: "电驱动",
    primaryThemeId: "new-energy-vehicles",
    subThemeId: "electric-drive",
    relatedThemeIds: ["new-energy-vehicles"],
    aliases: ["三电系统", "电机电控"],
    industrialChainRole: "整车三电",
    isThemeCenter: false,
    relationshipNote: "新能源车核心三电系统分支，电机、电控和变速箱总成。"
  },
  {
    id: "autonomous-driving",
    name: "智能驾驶",
    shortName: "智能驾驶",
    primaryThemeId: "new-energy-vehicles",
    subThemeId: "autonomous-driving-st",
    relatedThemeIds: ["new-energy-vehicles", "ai-computing"],
    aliases: ["自动驾驶", "ADAS"],
    industrialChainRole: "智能驾驶",
    isThemeCenter: false,
    relationshipNote: "智能驾驶算法与系统集成分支，与AI算力需求紧密相连。"
  },
  {
    id: "lidar",
    name: "激光雷达",
    shortName: "激光雷达",
    primaryThemeId: "new-energy-vehicles",
    subThemeId: "autonomous-driving-st",
    relatedThemeIds: ["new-energy-vehicles", "semiconductors"],
    aliases: ["LiDAR", "车载雷达"],
    industrialChainRole: "智能驾驶",
    isThemeCenter: false,
    relationshipNote: "智能驾驶感知硬件分支，与半导体光电器件高度交叉。"
  },
  {
    id: "automotive-chips",
    name: "车规芯片",
    shortName: "车规芯片",
    primaryThemeId: "new-energy-vehicles",
    subThemeId: "smart-cockpit-st",
    relatedThemeIds: ["new-energy-vehicles", "semiconductors"],
    aliases: ["汽车芯片", "车规级芯片"],
    industrialChainRole: "智能驾驶",
    isThemeCenter: false,
    relationshipNote: "智能驾驶和车控系统的核心芯片分支，与半导体国产化密切相关。"
  },
  {
    id: "smart-cockpit",
    name: "智能座舱",
    shortName: "智能座舱",
    primaryThemeId: "new-energy-vehicles",
    subThemeId: "smart-cockpit-st",
    relatedThemeIds: ["new-energy-vehicles", "consumer-electronics"],
    aliases: ["车载座舱", "数字座舱"],
    industrialChainRole: "智能驾驶",
    isThemeCenter: false,
    relationshipNote: "智能座舱人机交互分支，与消费电子显示和声学器件交叉。"
  },
  {
    id: "v2x-communication",
    name: "V2X车联网",
    shortName: "V2X",
    primaryThemeId: "new-energy-vehicles",
    subThemeId: "v2x",
    relatedThemeIds: ["new-energy-vehicles", "digital-economy"],
    aliases: ["车路协同", "C-V2X"],
    industrialChainRole: "车联网",
    isThemeCenter: false,
    relationshipNote: "车路协同通信分支，连接智能驾驶与数字经济基础设施。"
  },

  // ─── 消费电子/VR (7 sectors) ───
  {
    id: "consumer-electronics",
    name: "消费电子/VR",
    shortName: "消费电子",
    primaryThemeId: "consumer-electronics",
    subThemeId: "terminal-devices",
    relatedThemeIds: ["consumer-electronics"],
    aliases: ["消费电子主线"],
    industrialChainRole: "主线中心",
    isThemeCenter: true,
    relationshipNote: "消费电子与VR主题中心，覆盖终端设备、核心零部件和创新产品形态。"
  },
  {
    id: "smartphones",
    name: "智能手机",
    shortName: "智能手机",
    primaryThemeId: "consumer-electronics",
    subThemeId: "terminal-devices",
    relatedThemeIds: ["consumer-electronics"],
    aliases: ["手机", "移动终端"],
    industrialChainRole: "终端设备",
    isThemeCenter: false,
    relationshipNote: "消费电子最大终端设备分支，驱动上游零部件需求。"
  },
  {
    id: "vr-ar-devices",
    name: "VR/AR设备",
    shortName: "VR/AR",
    primaryThemeId: "consumer-electronics",
    subThemeId: "vr-ar",
    relatedThemeIds: ["consumer-electronics", "semiconductors"],
    aliases: ["XR设备", "头显"],
    industrialChainRole: "终端设备",
    isThemeCenter: false,
    relationshipNote: "沉浸式终端设备分支，与半导体显示和光学器件紧密关联。"
  },
  {
    id: "display-panels",
    name: "显示面板",
    shortName: "显示面板",
    primaryThemeId: "consumer-electronics",
    subThemeId: "core-components-ce",
    relatedThemeIds: ["consumer-electronics", "semiconductors"],
    aliases: ["面板", "OLED面板"],
    industrialChainRole: "核心零部件",
    isThemeCenter: false,
    relationshipNote: "消费电子核心显示组件分支，与半导体制造工艺高度关联。"
  },
  {
    id: "acoustic-devices",
    name: "声学器件",
    shortName: "声学器件",
    primaryThemeId: "consumer-electronics",
    subThemeId: "optical-acoustic",
    relatedThemeIds: ["consumer-electronics"],
    aliases: ["扬声器", "音频器件"],
    industrialChainRole: "核心零部件",
    isThemeCenter: false,
    relationshipNote: "消费电子声学交互核心零部件分支。"
  },
  {
    id: "optical-lenses",
    name: "光学镜头",
    shortName: "光学镜头",
    primaryThemeId: "consumer-electronics",
    subThemeId: "optical-acoustic",
    relatedThemeIds: ["consumer-electronics"],
    aliases: ["摄像头镜头", "光学组件"],
    industrialChainRole: "核心零部件",
    isThemeCenter: false,
    relationshipNote: "消费电子影像核心光学组件分支，也服务车载和安防场景。"
  },
  {
    id: "wearable-devices",
    name: "可穿戴设备",
    shortName: "可穿戴",
    primaryThemeId: "consumer-electronics",
    subThemeId: "vr-ar",
    relatedThemeIds: ["consumer-electronics", "digital-economy"],
    aliases: ["智能手表", "智能穿戴"],
    industrialChainRole: "终端设备",
    isThemeCenter: false,
    relationshipNote: "消费电子创新终端分支，与数字健康和物联网场景交叉。"
  },

  // ─── 数字经济/数据要素 (8 sectors) ───
  {
    id: "digital-economy",
    name: "数字经济/数据要素",
    shortName: "数字经济",
    primaryThemeId: "digital-economy",
    subThemeId: "data-elements-st",
    relatedThemeIds: ["digital-economy"],
    aliases: ["数字经济主线"],
    industrialChainRole: "主线中心",
    isThemeCenter: true,
    relationshipNote: "数字经济主题中心，覆盖数据要素、云软件和信创国产化。"
  },
  {
    id: "data-elements",
    name: "数据要素",
    shortName: "数据要素",
    primaryThemeId: "digital-economy",
    subThemeId: "data-elements-st",
    relatedThemeIds: ["digital-economy"],
    aliases: ["数据资产", "数据交易"],
    industrialChainRole: "数据要素",
    isThemeCenter: false,
    relationshipNote: "数据要素确权、流通和交易分支，数字经济的基础资源层。"
  },
  {
    id: "data-security",
    name: "数据安全",
    shortName: "数据安全",
    primaryThemeId: "digital-economy",
    subThemeId: "security-software",
    relatedThemeIds: ["digital-economy"],
    aliases: ["隐私计算", "数据合规"],
    industrialChainRole: "数据要素",
    isThemeCenter: false,
    relationshipNote: "数据安全与隐私保护分支，数据要素流通的基础保障。"
  },
  {
    id: "cloud-computing",
    name: "云计算",
    shortName: "云计算",
    primaryThemeId: "digital-economy",
    subThemeId: "cloud-software",
    relatedThemeIds: ["digital-economy", "ai-computing"],
    aliases: ["公有云", "云服务"],
    industrialChainRole: "云计算",
    isThemeCenter: false,
    relationshipNote: "数字经济的算力基础设施分支，与AI算力需求高度共振。"
  },
  {
    id: "saas-enterprise-software",
    name: "SaaS/企业软件",
    shortName: "SaaS",
    primaryThemeId: "digital-economy",
    subThemeId: "cloud-software",
    relatedThemeIds: ["digital-economy"],
    aliases: ["企业软件", "SaaS服务"],
    industrialChainRole: "云计算",
    isThemeCenter: false,
    relationshipNote: "企业级SaaS软件分支，云计算落地应用的重要形态。"
  },
  {
    id: "xinchuang",
    name: "信创",
    shortName: "信创",
    primaryThemeId: "digital-economy",
    subThemeId: "xinchuang",
    relatedThemeIds: ["digital-economy", "ai-computing"],
    aliases: ["信息技术应用创新", "信创产业"],
    industrialChainRole: "信创",
    isThemeCenter: false,
    relationshipNote: "信创国产化核心分支，涵盖CPU、OS和数据库等基础软件。"
  },
  {
    id: "os-database",
    name: "操作系统/数据库",
    shortName: "OS/数据库",
    primaryThemeId: "digital-economy",
    subThemeId: "xinchuang",
    relatedThemeIds: ["digital-economy", "ai-computing"],
    aliases: ["国产操作系统", "国产数据库"],
    industrialChainRole: "信创",
    isThemeCenter: false,
    relationshipNote: "信创基础软件分支，操作系统和数据库的国产替代。"
  },
  {
    id: "cybersecurity",
    name: "网络安全",
    shortName: "网络安全",
    primaryThemeId: "digital-economy",
    subThemeId: "security-software",
    relatedThemeIds: ["digital-economy"],
    aliases: ["信息安全", "网安"],
    industrialChainRole: "信创",
    isThemeCenter: false,
    relationshipNote: "网络安全与信创交叉分支，国产化安全产品需求持续增长。"
  },

  // ─── 金融科技 (6 sectors) ───
  {
    id: "fintech",
    name: "金融科技",
    shortName: "金融科技",
    primaryThemeId: "fintech",
    subThemeId: "fin-infra",
    relatedThemeIds: ["fintech"],
    aliases: ["金融科技主线"],
    industrialChainRole: "主线中心",
    isThemeCenter: true,
    relationshipNote: "金融科技主题中心，覆盖金融基础设施和金融应用创新。"
  },
  {
    id: "brokerage-it",
    name: "券商IT",
    shortName: "券商IT",
    primaryThemeId: "fintech",
    subThemeId: "fin-infra",
    relatedThemeIds: ["fintech"],
    aliases: ["证券IT", "券商信息化"],
    industrialChainRole: "金融基础设施",
    isThemeCenter: false,
    relationshipNote: "券商交易和信息系统分支，金融基础设施核心环节。"
  },
  {
    id: "payment-systems",
    name: "支付系统",
    shortName: "支付系统",
    primaryThemeId: "fintech",
    subThemeId: "fin-applications",
    relatedThemeIds: ["fintech", "digital-economy"],
    aliases: ["第三方支付", "移动支付"],
    industrialChainRole: "金融应用",
    isThemeCenter: false,
    relationshipNote: "支付清算系统分支，连接金融与数字经济的核心应用。"
  },
  {
    id: "digital-currency",
    name: "数字货币",
    shortName: "数字货币",
    primaryThemeId: "fintech",
    subThemeId: "digital-finance",
    relatedThemeIds: ["fintech", "digital-economy"],
    aliases: ["数字人民币", "DCEP"],
    industrialChainRole: "金融应用",
    isThemeCenter: false,
    relationshipNote: "数字货币研发与推广分支，与数字经济基础设施深度融合。"
  },
  {
    id: "financial-ai",
    name: "金融AI",
    shortName: "金融AI",
    primaryThemeId: "fintech",
    subThemeId: "digital-finance",
    relatedThemeIds: ["fintech", "ai-computing"],
    aliases: ["智能金融", "AI风控"],
    industrialChainRole: "金融基础设施",
    isThemeCenter: false,
    relationshipNote: "AI在金融场景的落地应用分支，与AI算力和算法能力交叉。"
  },
  {
    id: "insurance-tech",
    name: "保险科技",
    shortName: "保险科技",
    primaryThemeId: "fintech",
    subThemeId: "fin-applications",
    relatedThemeIds: ["fintech"],
    aliases: ["InsurTech", "智能保险"],
    industrialChainRole: "金融应用",
    isThemeCenter: false,
    relationshipNote: "保险行业数字化转型分支，涵盖智能核保和理赔自动化。"
  }
] satisfies readonly Sector[];

export const sectors: readonly Readonly<Sector>[] = Object.freeze(sectorConfig.map(freezeSector));
