/**
 * Backend ↔ frontend snapshot contract test.
 *
 * `backendSnapshot.sample.json` is generated by `scripts/dump_snapshot_fixture.py`
 * straight from the real `SnapshotRepository._expand` serializer — the same code
 * the Flask API uses. Parsing it here proves the producer's actual JSON shape
 * satisfies the consumer's strict validator.
 *
 * This closes the gap that let the missing per-point `tradeDate` bug ship: every
 * hand-written mock in the suite happened to include `tradeDate`, so the strict
 * validator was never exercised against the real (tradeDate-less) backend output.
 * Regenerate the fixture whenever the backend snapshot shape changes.
 */

import backendSnapshot from "../test/fixtures/backendSnapshot.sample.json";
import { parseSnapshot, InvalidSnapshotError } from "./capitalFlowSnapshot";

describe("backend snapshot contract", () => {
  it("accepts a snapshot serialized by the real backend (_expand)", () => {
    const snapshot = parseSnapshot(backendSnapshot);
    expect(snapshot.points.length).toBeGreaterThan(0);
    // Every point must carry the snapshot's trade date.
    for (const point of snapshot.points) {
      expect(point.tradeDate).toBe(snapshot.tradeDate);
    }
  });

  it("rejects the snapshot when points drop tradeDate (the UI-blocking bug)", () => {
    const broken = {
      ...backendSnapshot,
      points: (backendSnapshot.points as Record<string, unknown>[]).map((point) => {
        const { tradeDate: _omitted, ...rest } = point;
        return rest;
      }),
    };
    expect(() => parseSnapshot(broken)).toThrow(InvalidSnapshotError);
  });
});
